services:
 app:
  build: .
  ports: 
   - 3000:3000
  volumes:
    - ./src:/app/src
    # Esta variable de entorno sirve para activar hot reload de vite dentro del contenedor
  environment:
    - CHOKIDAR_USEPOLLING=true
  env_file: 
    ./.env
